# Generated by Django 4.2.7 on 2023-11-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LieuDepart', models.CharField(max_length=100)),
                ('LieuLivraison', models.CharField(max_length=100)),
                ('DateLivraison', models.DateField()),
                ('DescriptionColis', models.TextField()),
                ('StatutColis', models.BooleanField(default=False)),
                ('conducteur_accepte', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Correspondances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatutCorrespondance', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('terminee', 'Terminée'), ('autre', 'Autre')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Trajets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LieuDepart', models.CharField(max_length=100)),
                ('LieuArrivee', models.CharField(max_length=100)),
                ('DateHeureDepart', models.DateTimeField()),
                ('DescriptionTrajet', models.TextField()),
                ('EspaceColisDisponible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PrixTrajet', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=100)),
                ('MotDePasse', models.CharField(max_length=255)),
                ('TypeUtilisateur', models.CharField(choices=[('conducteur', 'Conducteur'), ('expediteur', 'Expéditeur')], max_length=20)),
            ],
        ),
    ]
