# Generated by Django 4.2.7 on 2023-11-18 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colis',
            options={'verbose_name': 'Colis', 'verbose_name_plural': 'Colis'},
        ),
    ]
